// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VendingMachine.Api.Data;

#nullable disable

namespace VendingMachine.Api.Migrations
{
    [DbContext(typeof(VendingMachineDbContext))]
    partial class VendingMachineDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VendingMachine.Api.Models.MachineCoinInventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("Denomination")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Denomination")
                        .IsUnique();

                    b.ToTable("CoinInventory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Count = 40,
                            Denomination = 5
                        },
                        new
                        {
                            Id = 2,
                            Count = 40,
                            Denomination = 10
                        },
                        new
                        {
                            Id = 3,
                            Count = 40,
                            Denomination = 25
                        },
                        new
                        {
                            Id = 4,
                            Count = 15,
                            Denomination = 100
                        });
                });

            modelBuilder.Entity("VendingMachine.Api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PriceCents")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SlotOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "A1",
                            Name = "Cola",
                            PriceCents = 125,
                            Quantity = 10,
                            SlotOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "A2",
                            Name = "Diet Cola",
                            PriceCents = 125,
                            Quantity = 8,
                            SlotOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Code = "A3",
                            Name = "Root Beer",
                            PriceCents = 125,
                            Quantity = 0,
                            SlotOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Code = "B1",
                            Name = "Orange Soda",
                            PriceCents = 150,
                            Quantity = 6,
                            SlotOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Code = "B2",
                            Name = "Sparkling Water",
                            PriceCents = 150,
                            Quantity = 12,
                            SlotOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            Code = "B3",
                            Name = "Bottled Water",
                            PriceCents = 100,
                            Quantity = 15,
                            SlotOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            Code = "C1",
                            Name = "Chips",
                            PriceCents = 175,
                            Quantity = 7,
                            SlotOrder = 7
                        },
                        new
                        {
                            Id = 8,
                            Code = "C2",
                            Name = "Pretzels",
                            PriceCents = 150,
                            Quantity = 0,
                            SlotOrder = 8
                        },
                        new
                        {
                            Id = 9,
                            Code = "C3",
                            Name = "Candy Bar",
                            PriceCents = 125,
                            Quantity = 20,
                            SlotOrder = 9
                        },
                        new
                        {
                            Id = 10,
                            Code = "D1",
                            Name = "Chocolate Bar",
                            PriceCents = 150,
                            Quantity = 9,
                            SlotOrder = 10
                        },
                        new
                        {
                            Id = 11,
                            Code = "D2",
                            Name = "Gum",
                            PriceCents = 75,
                            Quantity = 25,
                            SlotOrder = 11
                        },
                        new
                        {
                            Id = 12,
                            Code = "D3",
                            Name = "Crackers",
                            PriceCents = 175,
                            Quantity = 5,
                            SlotOrder = 12
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
